### PR TITLE
#50 Update system design diagram

### PR DESCRIPTION
**Pull request by rqding**

### CODE REVIEW

**Review by lwjohnst86 — CHANGES_REQUESTED** [review]
We don't need images of the slides (makes it hard to modify later on). Could you convert slides 5 and 6 into SVG files?

**Comment by rqding** [comment]
Sure @lwjohnst86  I added the two svg files in the system design svg folder

**Comment by lwjohnst86** [comment]
I don't know why the SVG images turned out so badly. Does PowerPoint not have better export capacity to SVG?

**Comment by lwjohnst86** [comment]
these are now covered by #87 so will close this.

**Pull request closed without merging**
